export default {
  // user authentication
  SET_USER_LOGIN: 'SET_USER_LOGIN',
  SET_USER_NAME: 'SET_USER_NAME',
  SET_USER_EMAIL: 'SET_USER_EMAIL',
  SET_USER_PASSWORD: 'SET_USER_PASSWORD',
  SET_USER_HAS_TOKEN: 'SET_USER_HAS_TOKEN',
  LOG_USER_OUT: 'LOG_USER_OUT',
  // user data
  SET_USER_SLEEP_HOURS: 'SET_USER_SLEEP_HOURS',
  SET_USER_MOOD: 'SET_USER_MOOD',
  SEND_USER_SLEEP_DATA: 'SEND_USER_SLEEP_DATA'
}